;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/weather]
type = custom/script

; Command to execute - Update path to where you place weather.sh
exec = ~/YourPath/weather.sh

; Seconds to sleep between updates (30 minutes)
interval = 1800

format = <label>
format-foreground = ${color.foreground}
label = " %output%"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_