;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network-wifi]
type = custom/script
exec = ~/YourPath/network-wifi.sh
interval = 1
tail = true
format = <label>
format-foreground = ${color.foreground}
label = "%{A1:~/YourPath/wifimenu.sh &:}%output%%{A}"
click-left = ~/YourPath/wifimenu.sh

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_