#!/usr/bin/env bash

# Copyright © 2024 Jesús Arenas

# Customized and enhanced by Anindra Mohan Trivedi

# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

print_usage() {
	echo -n "\
Usage: $program_name [OPTIONS...]

Displays a menu with a launcher to select a Wi-Fi network.

Options:
  -s, --submenu               Show Wi-Fi options in a submenu.
  -S, --no-submenu            Do not show Wi-Fi options in a submenu (default).
  -w, --wireguard             Show wireguard connections option.
  -W, --no-wireguard          Do not show wireguard connections option
                              (default).
  -j, --emoji                 Use emojis instead of Nerd Fonts font for icons.
  -J, --no-emoji              Use Nerd Fonts font instead of emojis for icons
                              (default).
  --no-notify                 Do not send notifications.

  -i INTERFACE
  --interface INTERFACE       Start using Wi-Fi interface INTERFACE.

  --wofi                      Use wofi launcher (default).
  --rofi                      Use rofi launcher.
  --wmenu                     Use wmenu launcher.
  --dmenu                     Use dmenu launcher.
  --bemenu                    Use bemenu launcher.
  --custom LAUNCHER 1 2 3     Use launcher LAUNCHER with options for
                              case-insensitive (1), case-sensitive (2)
                              and password-prompt (3) input.

  -h, --help                  Print this help and exit.
  -v, --version               Print version and other info and exit.

Nerd Fonts icons are used. A font can be downloaded at:
https://www.nerdfonts.com/

Dependencies: 
  - NetworkManager.
  - A menu launcher.

About dmenu: 
  Hide password button does not work, since dmenu does not support this.

Exit status: 
  Returns 1 if a wrong option is given.
  Returns 2 if no Wi-Fi interface is detected with nmcli.
            if an unknown interface is given with -i.
  Returns 3 if the launcher selected is not installed.
  Returns 4 if custom launcher options are not completely defined.
  Returns 0 otherwise.

This program is licensed under GPL-3.0-or-later.
"
	exit 0
}

print_about() {
	echo -n "\
wifimenu 2.7.1
Copyright © 2024 Jesús Arenas
Official repository: https://github.com/podobu/wifimenu
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
"
	exit 0
}

display_menu() {
	declare form=$1
	declare prompt="$2"
	
	case "$launcher" in
		'wofi')
			case $form in
				1) wofi --dmenu --insensitive --prompt "$prompt" ;;
				2) wofi --dmenu --prompt "$prompt" ;;
				3) wofi --dmenu --password --prompt "$prompt" ;;
			esac
			;;
		'rofi')
			case $form in
				1) rofi -dmenu -i -p "$prompt" -theme ~/.config/polybar/forest/scripts/rofi/launcher.rasi -theme-str "window { width: 30%; } element { padding: 8px 8px 8px -15px; } prompt { font: \"Iosevka Nerd Font 10\"; } listview { lines: 8; }" ;;
				2) rofi -dmenu -p "$prompt" -theme ~/.config/polybar/forest/scripts/rofi/launcher.rasi -theme-str "window { width: 30%; } element { padding: 8px 8px 8px -15px; } prompt { font: \"Iosevka Nerd Font 10\"; } listview { lines: 8; }" ;;
				3) rofi -dmenu -password -p "$prompt" -theme ~/.config/polybar/forest/scripts/rofi/launcher.rasi -theme-str "window { width: 30%; }" ;;
			esac
			;;
		'wmenu')
			case $form in
				1) wmenu -l 10 -i -p "$prompt" ;;
				2) wmenu -l 10 -p "$prompt" ;;
				3) wmenu -l 10 -P -p "$prompt" ;;
			esac
			;;
		'dmenu')
			case $form in
				1) dmenu -l 10 -i -p "$prompt" ;;
				2) dmenu -l 10 -p "$prompt" ;;
				3) dmenu -l 10 -p "$prompt" ;; # Cannot hide the password
			esac
			;;
		'bemenu')
			case $form in
				1) bemenu --list 10 --ignorecase --prompt "$prompt" ;;
				2) bemenu --list 10 --prompt "$prompt" ;;
				3) bemenu --list 10 --password "indicator" --prompt "$prompt" ;;
			esac
			;;
		'custom')
			case $form in
				1) "${custom_opts[launcher]}" ${custom_opts[insensitive]} "$prompt" ;;
				2) "${custom_opts[launcher]}" ${custom_opts[sensitive]} "$prompt" ;;
				3) "${custom_opts[launcher]}" ${custom_opts[password]} "$prompt" ;;
			esac
			;;
		*)
			echo "$program_name: Unknown launcher. See variable 'launcher'." >&2
			exit 1
			;;
	esac
}

send_notification() {
	[ -z "$notifications" ] && return
	declare specific icon
	declare summary="$3"
	declare body="$4"
	# Notification category format specified by freedesktop.org
	case "$1" in
		1) specific='connected' ;;
		2) specific='disconnected' ;;
		3) specific='error' ;;
	esac
	# Icon naming format specified by freedesktop.org
	case "$2" in
		1) icon='network-wireless' ;;
		2) icon='network-offline' ;;
		3) icon='network-transmit-receive' ;;
		4) icon='network-error' ;;
	esac
	notify-send --app-name "$program_name" --category "network.$specific" --icon "$icon" --transient "$summary" "$body"
}

ask_password() {
	declare middle_option=${1:-}
	declare wifi_password="$icon_eye"
	until [[ -z "$wifi_password" || "$wifi_password" == !(${icon_eye_closed}*|${icon_eye}*|${icon_unlock}*) ]]; do
		if [[ "$wifi_password" =~ ^$icon_eye_closed ]]; then
			wifi_password=$(echo -e "$icon_eye${middle_option}\n$icon_close" | display_menu 3 "$tr_ask_password_prompt")
		elif [[ "$wifi_password" =~ ^$icon_unlock ]]; then
			wifi_password=""
		else
			wifi_password=$(echo -e "$icon_eye_closed${middle_option}\n$icon_close" | display_menu 2 "$tr_ask_password_prompt")
		fi
	done
	echo "$wifi_password"
}

select_interface() {
	chosen=$( (for (( i = 0; i < ${#interfaces[@]}; i++ )); do echo "$icon_interface  ${interfaces[$i]}" ; done; echo "$icon_close") | display_menu 1 "$tr_select_interface_prompt")

	if [ -z "$chosen" ]; then
		exit 0
	elif [[ "$chosen" =~ ^$icon_close ]]; then
		return
	else
		interface_to_use="${chosen:3}"
	fi
}

menu_addresses() {
	declare connection="$1"
	declare ipv="$2"
	declare -a addresses_list
	declare -i addresses_list_length
	declare sure
	while true; do
		addresses_list=($(nmcli --get-values ipv${ipv}.addresses connection show $connection | sed 's/,//g'))
		chosen="$( (for i in "${addresses_list[@]}"; do echo "$i"; done; echo "$icon_close") | display_menu 1 "$tr_menu_addresses_prompt")"

		if [ -z "$chosen" ]; then
			exit 0
		elif [[ "$chosen" =~ ^$icon_close ]]; then
			return
		fi

		addresses_list_length=${#addresses_list[@]}

		for ((i=0; i < $addresses_list_length; i++)) do
			if [ "$chosen" = "${addresses_list[$i]}" ]; then
				sure=$(echo -e "$icon_check\n$icon_close" | display_menu 1 "$tr_menu_addresses_sure_prompt_1 ${chosen}$tr_menu_addresses_sure_prompt_2")
				if [ -z "$sure" ]; then
					exit 0
				elif [[ "$sure" =~ ^$icon_check ]]; then
					if [ $addresses_list_length -eq 1 ]; then
						nmcli connection modify uuid "$connection" ipv${ipv}.gateway ''
						nmcli connection modify uuid "$connection" ipv${ipv}.method auto
					fi
					nmcli connection modify uuid "$connection" -ipv${ipv}.addresses $chosen
					[ $addresses_list_length -eq 1 ] && break 2
				fi
				continue 2
			fi
		done

		nmcli connection modify uuid "$connection" +ipv${ipv}.addresses $chosen

	done
}

menu_ip_config() {
	declare chosen_connection="$1"
	declare connection="$2"
	declare ipv="$3"
	declare autoip_state autodns_state message new_addresses new_gateway
	while true; do
		autoip_state="$([ "$(nmcli --get-values ipv${ipv}.method connection show "$connection")" = "auto" ] && echo "$icon_on" || echo "$icon_off")"

		if [ "$autoip_state" = "$icon_on" ]; then
			autodns_state="$([ "$(nmcli --get-values ipv${ipv}.ignore-auto-dns connection show "$connection")" = "no" ] && echo "$icon_on" || echo "$icon_off")"
			message="$autodns_message  $autodns_state"
		else
			message="$address_message\n$gateway_message $(nmcli --get-values ipv${ipv}.gateway connection show "$connection")"
		fi

		chosen="$(echo -e "$autoip_message  $autoip_state\n$message\n$icon_close" | display_menu 1 "$chosen_connection")"

		case "$chosen" in
			'') exit 0 ;;
			"$icon_close"*) return ;;
			"$icon_net_1"*)
				if [ "$autoip_state" = "$icon_on" ]; then
					if [ -z "$(nmcli --get-values ipv4.addresses connection show "$connection")" ]; then
						new_addresses="$(echo "$icon_close" | display_menu 1 "$tr_menu_ip_config_addresses_prompt")"
						if [ -z "$new_addresses" ]; then
							exit 0
						elif [[ "$new_addresses" =~ ^$icon_close ]]; then
							continue
						fi
						nmcli connection modify uuid "$connection" ipv${ipv}.addresses "$new_addresses" || continue
					fi
					nmcli connection modify uuid "$connection" ipv${ipv}.method manual
				else
					nmcli connection modify uuid "$connection" ipv${ipv}.gateway ''
					nmcli connection modify uuid "$connection" ipv${ipv}.method auto
				fi
				;;
			"$icon_net_4"*) [ "$autodns_state" = "$icon_on" ] && nmcli connection modify uuid "$connection" ipv${ipv}.ignore-auto-dns yes || nmcli connection modify uuid "$connection" ipv${ipv}.ignore-auto-dns no ;;
			"$icon_net_3"*) menu_addresses "$connection" "$ipv" ;;
			"$icon_net_2"*)
				new_gateway="$(echo "$icon_close" | display_menu 1 "$tr_menu_ip_config_gateway_prompt")"
				if [ -z "$new_gateway" ]; then
					exit 0
				elif [[ "$new_gateway" =~ ^$icon_close ]]; then
					continue
				fi
				nmcli connection modify uuid "$connection" ipv${ipv}.gateway "$new_gateway"
				;;
		esac
	done
}

menu_dns() {
	declare connection="$1"
	declare ipv="$2"
	declare -a dns_list
	declare sure
	while true; do
		dns_list=($(nmcli --get-values ipv${ipv}.dns connection show $connection | sed 's/,/ /g'))
		chosen="$( (for i in "${dns_list[@]}"; do echo "$i"; done; echo "$icon_close") | display_menu 1 "$tr_menu_dns_prompt")"

		if [ -z "$chosen" ]; then
			exit 0
		elif [[ "$chosen" =~ ^$icon_close ]]; then
			return
		fi

		for ((i=0; i < ${#dns_list[@]}; i++)) do
			if [ "$chosen" = "${dns_list[$i]}" ]; then
				sure=$(echo -e "$icon_check\n$icon_close" | display_menu 1 "$tr_menu_dns_sure_prompt_1 ${chosen}$tr_menu_dns_sure_prompt_2")
				if [ -z "$sure" ]; then
					exit 0
				elif [[ "$sure" =~ ^$icon_check ]]; then
					nmcli connection modify uuid "$connection" -ipv${ipv}.dns $chosen
				fi
				continue 2
			fi
		done

		nmcli connection modify uuid "$connection" +ipv${ipv}.dns $chosen

	done
}

forget_connection() {
	declare chosen_connection="$1"
	declare connection="$2"
	declare sure="$(echo -e "$icon_check\n$icon_close" | display_menu 1 "$tr_forget_connection_sure_prompt_1 ${chosen_connection}$tr_forget_connection_sure_prompt_2")"

	if [ -z "$sure" ]; then
		exit 0
	elif [[ "$sure" =~ ^$icon_check ]]; then
		nmcli connection delete uuid "$connection" && return 0
	fi

	return 1
}

rename_connection() {
	declare connection="$1"
	new_name="$(echo "$icon_close" | display_menu 1 "$tr_rename_connection_prompt")"

	if [ -z "$new_name" ]; then
		exit 0
	elif [[ "$new_name" =~ ^$icon_close ]]; then
		return 1
	fi

	nmcli connection modify uuid "$connection" connection.id "$new_name"
}

menu_connection() {
	declare chosen_connection="$1"
	declare connection="$2"
	declare autoconnect_state
	while true; do
		autoconnect_state="$([ "$(nmcli --get-values connection.autoconnect connection show "$connection")" = "yes" ] && echo "$icon_on" || echo "$icon_off")"
		chosen="$(echo -e "$autoconnect_message  $autoconnect_state\n$ipv4_config_message\n$dns4_message\n$ipv6_config_message\n$dns6_message\n$forget_message\n$icon_close" | display_menu 1 "$chosen_connection")"

		case "$chosen" in
			'') exit 0 ;;
			"$icon_close"*) return ;;
			"$icon_automatic"*) [ "$autoconnect_state" = "$icon_on" ] && nmcli connection modify uuid "$connection" autoconnect no || nmcli connection modify uuid "$connection" autoconnect yes ;;
			"$icon_4_1"*) menu_ip_config "$@" "4" ;;
			"$icon_4_2"*) menu_dns "$connection" "4" ;;
			"$icon_6_1"*) menu_ip_config "$@" "6" ;;
			"$icon_6_2"*) menu_dns "$connection" "6" ;;
			"$icon_trash"*) forget_connection "$@" && return ;;
		esac
	done
}

menu_wireguard_connection(){
	declare chosen_connection="$1"
	declare connection="$2"
	declare state autoconnect_state new_name
	while true; do
		state="$([ "$(nmcli --get-values GENERAL.STATE connection show "$connection")" = "activated" ] && echo "$icon_on" || echo "$icon_off")"
		autoconnect_state="$([ "$(nmcli --get-values connection.autoconnect connection show "$connection")" = "yes" ] && echo "$icon_on" || echo "$icon_off")"
		chosen="$(echo -e "$wireguard_enable_message  $state\n$autoconnect_message  $autoconnect_state\n$rename_connection_message\n$forget_message\n$icon_close" | display_menu 1 "$chosen_connection")"

		case "$chosen" in
			'') exit 0 ;;
			"$icon_close"*) return ;;
			"$icon_plug"*) [ "$state" = "$icon_on" ] && {
					nmcli connection down uuid "$connection" && 
						send_notification 1 2 "$tr_notice_disconnected_summary" "$tr_notice_disconnected_vpn_body" ||
						send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_vpn_disconnection_body"
				} || {
					nmcli connection up uuid "$connection" &&
						send_notification 1 3 "$tr_notice_connected_summary" "$tr_notice_connected_vpn_body" ||
						send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_vpn_connection_body"
				}
				;;
			"$icon_automatic"*) [ "$autoconnect_state" = "$icon_on" ] && nmcli connection modify uuid "$connection" autoconnect no || nmcli connection modify uuid "$connection" autoconnect yes ;;
			"$icon_pen"*) rename_connection "$connection" && chosen_connection="$new_name" ;;
			"$icon_trash"*) forget_connection "$@" && return ;;
		esac
	done
}

menu_known_connections() {
	case "$1" in
		"wifi" | "802-11-wireless")
			connection_type="802-11-wireless"
			icon="$icon_wireless"
			menu_type="menu_connection"
			;;
		"wireguard")
			connection_type="$1"
			icon="$icon_net_5"
			menu_type="menu_wireguard_connection"
			;;
	esac
	declare -a profiles_list
	while true; do

		mapfile -t profiles_list < <(nmcli --colors no --get-values TYPE,UUID,NAME connection show | awk -F ':' -v ct="$connection_type" -v icon="$icon" '$1 == ct {print $2 "\\0" icon "  " $3}')
		
		# Get currently connected network (if any)
		current_conn=$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null | grep ":wlan0$" | cut -d: -f1)
		
		# Build menu options - show saved networks + remove option + close
		menu_options=""
		for i in "${profiles_list[@]}"; do
			net_name=$(echo -e "$i" | cut --delimiter $'\0' --fields 2)
			[ -n "$net_name" ] && menu_options="${menu_options}${net_name}"$'\n'
		done
		menu_options="${menu_options}${remove_all_networks_message}"$'\n'
		menu_options="${menu_options}${icon_close}  Back"
		
		chosen=$(echo -e "$menu_options" | display_menu 1 "$tr_known_connections_message")

		if [ -z "$chosen" ]; then
			exit 0
		elif [[ "$chosen" =~ ^$icon_close ]]; then
			return
		elif [[ "$chosen" =~ ^$icon_trash ]]; then
			# Remove all saved networks except currently connected one
			sure=$(echo -e "$icon_check\n$icon_close" | display_menu 2 "Remove all saved networks? Current connection '$current_conn' will be kept.")
			if [[ "$sure" =~ ^$icon_check ]]; then
				# If connected and not saved, save it first
				if [ -n "$current_conn" ]; then
					nmcli connection show "$current_conn" >/dev/null 2>&1 || nmcli connection save "$current_conn" >/dev/null 2>&1 || true
				fi
				
				# Get fresh list of saved connections
				all_conns=$(nmcli -t -f NAME connection show 2>/dev/null)
				
				deleted_count=0
				while IFS= read -r net_name; do
					[ -z "$net_name" ] && continue
					[ "$net_name" = "$current_conn" ] && continue
					[ "$net_name" = "lo" ] && continue
					[[ "$net_name" =~ ^Wired ]] && continue
					nmcli connection delete id "$net_name" 2>/dev/null && deleted_count=$((deleted_count + 1)) || true
				done <<< "$all_conns"
				
				send_notification 1 1 "Networks Removed" "$deleted_count saved networks deleted (current kept)"
			fi
			continue
		fi

		for i in "${profiles_list[@]}"; do
			if [ "$chosen" = "$(echo -e "$i" | cut --delimiter $'\0' --fields 2)" ]; then
				eval "$menu_type \"$(sed 's/"/\\"/g' <<< "${chosen}")\" \"$(echo -e "$i" | cut --delimiter $'\0' --fields 1)\""
				break
			fi
		done
		
	done
}

connect_hidden() {
	declare wifi_name="$(echo "$icon_close"| display_menu 2 "$tr_connect_hidden_prompt")"

	if [ -z "$wifi_name" ]; then
		exit 0
	elif [[ "$wifi_name" =~ ^$icon_close ]]; then
		return
	fi

	declare wifi_password="$(ask_password "\n$icon_unlock")"

	if [ -z "$wifi_password" ]; then
		exit 0
	elif [[ "$wifi_password" =~ ^$icon_unlock ]]; then
		wifi_password=""
	elif [[ "$wifi_password" =~ ^$icon_close ]]; then
		return
	fi

	nmcli --wait 15 device wifi connect "$wifi_name" hidden yes password "$wifi_password" &&
		send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body" ||
		send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_wifi_connection_body"
}

connect_wifi() {
	# Get script directory for log file
	SDIR="$(dirname "$0")"
	
	# Extract SSID - remove icon, (connected), signal bars, saved indicator, and (Try Again)
	declare wifi_ssid
	wifi_ssid=$(echo "$1" | sed 's/^[^ ]*  //' | sed 's/ (connected)//' | sed 's/ (.*//' | sed 's/ (𝙏𝙧𝙮 𝘼𝙜𝙖𝙞𝙣)//' | sed 's/ 󱣪$//' | sed 's/ 󰢾$//' | sed 's/ 󰢽$//' | sed 's/ 󰢼$//' | sed 's/ 󰢿$//')
	
	# Trim whitespace
	wifi_ssid=$(echo "$wifi_ssid" | xargs)
	
	# Check if this network is currently connected
	current_conn=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
	if [ "$wifi_ssid" = "$current_conn" ]; then
		# Network is already connected - disconnect instead
		# Disable autoconnect for ALL WiFi connections to prevent auto-reconnect
		for conn in $(nmcli -t -f NAME,TYPE connection show | grep ":wifi$" | cut -d: -f1); do
			nmcli connection modify "$conn" connection.autoconnect-slaves no >/dev/null 2>&1 || true
			nmcli connection modify "$conn" autoconnect no >/dev/null 2>&1 || true
		done
		# Disconnect device to ensure no auto-reconnect
		nmcli device disconnect wlan0 >/dev/null 2>&1 || true
		sleep 1
		send_notification 2 2 "$tr_notice_disconnected_summary" "$tr_notice_disconnected_wifi_body"
		exit 0
	fi
	
	# Before connecting, ensure all other networks have autoconnect disabled
	for conn in $(nmcli -t -f NAME,TYPE connection show | grep ":wifi$" | cut -d: -f1); do
		nmcli connection modify "$conn" connection.autoconnect-slaves no >/dev/null 2>&1 || true
		[ "$conn" != "$wifi_ssid" ] && nmcli connection modify "$conn" autoconnect no >/dev/null 2>&1 || true
	done
	
	# Enable autoconnect only for the network we're connecting to
	nmcli connection modify "$wifi_ssid" autoconnect yes >/dev/null 2>&1 || true
	
	# Debug
	echo "Connecting to: '$wifi_ssid'" >> "$SDIR/wifi-connect.log"
	echo "Menu item: '$1'" >> "$SDIR/wifi-connect.log"
	
	# Check if network is a Try Again (previously saved, now deleted)
	try_again_network=$(cat "$SDIR/.pending_network" 2>/dev/null)
	is_try_again=0
	[ -n "$try_again_network" ] && [ "$wifi_ssid" = "$try_again_network" ] && is_try_again=1
	
	# Check if network exists in saved connections
	nmcli -t -f NAME connection show 2>/dev/null | grep -qxF "$wifi_ssid"
	saved_result=$?
	
	# Handle Try Again first
	if [ $is_try_again -eq 1 ]; then
		rm -f "$SDIR/.pending_network"
		declare wifi_password=$(ask_password)
		[ -z "$wifi_password" ] && return
		[[ "$wifi_password" == "$icon_close"* ]] && return
		
		nmcli device wifi connect "$wifi_ssid" password "$wifi_password" >/dev/null 2>&1
		sleep 3
		if nmcli -t -f NAME,DEVICE connection show --active | grep -q ":wlan0"; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			rm -f "$SDIR/.pending_network"
			echo "Try Again success - exiting 0" >> "$SDIR/wifi-connect.log"
			exit 0
		else
			send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_wifi_connection_body"
			echo "Try Again failed - exiting 42" >> "$SDIR/wifi-connect.log"
			exit 42
		fi
	fi
	
	# Handle saved networks
	if [ $saved_result -eq 0 ]; then
		# Use timeout to prevent hanging when password is wrong
		# KDE dialog might appear but we don't wait for it
		nmcli_output=$(timeout 3 nmcli -a connection up id "$wifi_ssid" 2>&1)
		result=$?
		
		# Check for actual failure indicators (not just "password" which appears in normal output)
		failed=0
		[ $result -ne 0 ] && failed=1
		echo "$nmcli_output" | grep -qi "error\|failed\|disconnected" && failed=1
		
		if [ $failed -eq 1 ]; then
			# Delete saved connection to clear old data
			nmcli connection delete id "$wifi_ssid" >/dev/null 2>&1 || true
			# Set as pending for Try Again
			echo "$wifi_ssid" > "$SDIR/.pending_network"
			exit 42
		fi
		
		# Verify actually connected
		if nmcli -t -f NAME,DEVICE connection show --active | grep -q ":wlan0"; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			exit 0
		fi
		
		# Connected but not on wlan0 - might be connected elsewhere
		send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
		exit 0
	fi
	
	# Check if network exists in saved connections
	nmcli -t -f NAME connection show 2>/dev/null | grep -qxF "$wifi_ssid"
	saved_result=$?
	# Handle Try Again first - network was previously saved but now deleted
	if [ $is_try_again -eq 1 ]; then
		rm -f "$SDIR/.pending_network"
		
		# Delete any existing connection with this SSID to avoid conflicts
		nmcli connection delete id "$wifi_ssid" >/dev/null 2>&1 || true
		
		# Disable autoconnect for all saved connections first
		nmcli -t -f NAME connection show | while read conn; do
			nmcli connection modify "$conn" autoconnect no >/dev/null 2>&1 || true
		done
		
		# Disconnect current network first
		nmcli device disconnect wlan0 >/dev/null 2>&1 || true
		sleep 2
		
		declare wifi_password=$(ask_password)
		[ -z "$wifi_password" ] && return
		[[ "$wifi_password" == "$icon_close"* ]] && return
		
		# Connect with password - force wlan0 interface
		nmcli device wifi connect "$wifi_ssid" password "$wifi_password" ifname wlan0 >/dev/null 2>&1
		
		# Wait up to 10 seconds for connection to establish
		for i in 1 2 3 4 5; do
			sleep 2
			connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
			echo "Attempt $i: connected to '$connected_ssid', expected '$wifi_ssid'" >> "$SDIR/wifi-connect.log"
			if [ "$connected_ssid" = "$wifi_ssid" ]; then
				break
			fi
		done
		
		# Check if connected to the correct network
		connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
		if [ "$connected_ssid" = "$wifi_ssid" ]; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			# Success - clear pending network so it doesn't show Try Again anymore
			rm -f "$SDIR/.pending_network"
			# Success - close menu
			exit 0
		else
			# Try one more time after another disconnect
			nmcli device disconnect wlan0 >/dev/null 2>&1 || true
			sleep 2
			nmcli device wifi connect "$wifi_ssid" password "$wifi_password" ifname wlan0 >/dev/null 2>&1
			sleep 5
			
			connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
			if [ "$connected_ssid" = "$wifi_ssid" ]; then
				send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
				rm -f "$SDIR/.pending_network"
				exit 0
			else
				send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_wifi_connection_body"
				echo "Returning to menu with exit 42..." >> "$SDIR/wifi-connect.log"
				exit 42
			fi
		fi
	fi
	# Handle saved networks - try to connect, show Try Again on failure
	if [ $saved_result -eq 0 ]; then
		nmcli_output=$(timeout 3 nmcli -a connection up id "$wifi_ssid" 2>&1)
		result=$?
		
		# Any issue - set as Try Again
		if [ $result -ne 0 ] || echo "$nmcli_output" | grep -qi "error\|failed\|disconnected"; then
			nmcli connection delete id "$wifi_ssid" >/dev/null 2>&1 || true
			echo "$wifi_ssid" > "$SDIR/.pending_network"
			exit 42
		fi
		
		# Success
		send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
		exit 0
	fi
	# Check if network exists in saved connections
	nmcli -t -f NAME connection show 2>/dev/null | grep -qxF "$wifi_ssid"
	saved_result=$?
	echo "Saved result: $saved_result (0=found)" >> "$SDIR/wifi-connect.log"
	if [ $is_try_again -eq 1 ]; then
		# Try Again - prompt for password
		rm -f "$SDIR/.pending_network"
		
		# Delete any existing connection with this SSID to avoid conflicts
		nmcli connection delete id "$wifi_ssid" >/dev/null 2>&1 || true
		
		# Disable autoconnect for all saved connections first
		nmcli -t -f NAME connection show | while read conn; do
			nmcli connection modify "$conn" autoconnect no >/dev/null 2>&1 || true
		done
		
		# Disconnect current network first
		nmcli device disconnect wlan0 >/dev/null 2>&1 || true
		sleep 2
		
		declare wifi_password=$(ask_password)
		
		if [ -z "$wifi_password" ]; then
			# No password entered - return to menu
			return
		fi
		if [[ "$wifi_password" == "$icon_close"* ]]; then
			# User cancelled - return to menu
			return
		fi
		
		# Connect with password - force wlan0 interface
		nmcli device wifi connect "$wifi_ssid" password "$wifi_password" ifname wlan0 >/dev/null 2>&1
		
		# Wait up to 10 seconds for connection to establish
		for i in 1 2 3 4 5; do
			sleep 2
			connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
			if [ "$connected_ssid" = "$wifi_ssid" ]; then
				break
			fi
		done
		
		# Check if connected to the correct network
		connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
		if [ "$connected_ssid" = "$wifi_ssid" ]; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			# Success - clear pending network so it doesn't show Try Again anymore
			rm -f "$SDIR/.pending_network"
			# Success - close menu
			exit 0
		else
			# Try one more time after another disconnect
			nmcli device disconnect wlan0 >/dev/null 2>&1 || true
			sleep 2
			nmcli device wifi connect "$wifi_ssid" password "$wifi_password" ifname wlan0 >/dev/null 2>&1
			sleep 5
			
			connected_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
			if [ "$connected_ssid" = "$wifi_ssid" ]; then
				send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
				rm -f "$SDIR/.pending_network"
				exit 0
			else
				send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_wifi_connection_body"
				echo "Returning to menu with exit 42..." >> "$SDIR/wifi-connect.log"
				exit 42
			fi
		fi
	fi
	if [ $saved_result -eq 0 ]; then
		# Try to connect first - if password correct, works without KDE dialog
		nmcli_output=$(timeout 3 nmcli -a connection up id "$wifi_ssid" 2>&1)
		result=$?
		
		# Check for actual failure indicators (not just "password" which appears in normal output)
		if [ $result -ne 0 ] || echo "$nmcli_output" | grep -qi "error\|failed\|disconnected"; then
			# Delete saved connection to avoid issues on next attempt
			nmcli connection delete id "$wifi_ssid" >/dev/null 2>&1 || true
			# Set pending network for Try Again
			echo "$wifi_ssid" > "$SDIR/.pending_network"
			# Exit 42 to restart menu
			exit 42
		fi
		
		# Success - password was correct
		send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
		exit 0
	fi
	# Not saved - normal flow (check security and prompt)
	
	# Not saved and not Try Again - normal flow
	
	# Not saved - check if secured (use first character of menu item to detect security)
	declare wifi_security="${1:0:${#icon_wifi_1}}"
	if [[ "$wifi_security" =~ ^(${icon_wifi_1}|${icon_wifi_2}|${icon_wifi_3}) ]]; then
		declare wifi_password=$(ask_password)
		[ -z "$wifi_password" ] && return
		[[ "$wifi_password" =~ ^(${icon_close}|${icon_unlock}) ]] && return
		
		# Disconnect current network first
		nmcli device disconnect wlan0 >/dev/null 2>&1 || true
		sleep 1
		
		# Connect with password
		nmcli device wifi connect "$wifi_ssid" password "$wifi_password" >/dev/null 2>&1
		sleep 3
		# Check if connected
		if nmcli -t -f NAME,DEVICE connection show --active | grep -q ":wlan0"; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			# Success - clear pending network so it doesn't show Try Again anymore
			rm -f "$SDIR/.pending_network"
		else
			send_notification 3 4 "$tr_notice_error_summary" "$tr_notice_error_wifi_connection_body"
		fi
	else
		# Open network - connect directly
		# Disconnect current network first
		nmcli device disconnect wlan0 >/dev/null 2>&1 || true
		sleep 1
		
		nmcli device wifi connect "$wifi_ssid" >/dev/null 2>&1
		sleep 3
		if [ $? -eq 0 ]; then
			send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
			# Success - clear pending network so it doesn't show Try Again anymore
			rm -f "$SDIR/.pending_network"
		fi
	fi
	
	exit 0
}

menu_submenu() {
	while true; do
		chosen="$(echo -e "$disable_message\n${interfaces[1]:+$interface_message ${interface_to_use}\n}$known_connections_message\n${wireguard:+${wireguard_message}\n}$hidden_message\n$icon_close" | display_menu 1 "$tr_submenu_message")"
		case "$chosen" in
			'') exit 0 ;;
			"$icon_close"*) return ;;
			"$icon_wifi_disable"*) nmcli radio wifi off ; send_notification 1 1 "$tr_notice_disable_wifi_summary" "$tr_notice_disable_wifi_body" ; exit 0 ;;
			"$icon_interface"*) select_interface ;;
			"$icon_saved"*) menu_known_connections "wifi" ;;
			"$icon_dragon"*) menu_known_connections "wireguard" ;;
			"$icon_eye"*) connect_hidden ;;
		esac
	done
}

menu_network_info() {
	SDIR="$(dirname "$0")"
	echo "menu_network_info: START" >> "$SDIR/wifi-connect.log"
	while true; do
		echo "menu_network_info: loop start" >> "$SDIR/wifi-connect.log"
		
		# Get list of available networks with more details
		networks=$(nmcli -t -f SSID,SIGNAL,SECURITY,CHAN device wifi list --rescan auto | head -15 | grep -v '^:$')
		# Also filter out any empty lines
		networks=$(echo "$networks" | grep -v '^$')
		echo "networks output: '$networks'" >> "$SDIR/wifi-connect.log"
		
		# Build network list - filter out empty lines and empty SSIDs
		network_list=""
		while IFS=: read -r ssid signal security chan; do
			# Skip empty fields - all fields empty means blank line
			[ -z "$ssid" ] && [ -z "$signal" ] && continue
			# Skip empty SSIDs
			[ -z "$ssid" ] && continue
			# Skip if SSID is just whitespace
			[ -z "${ssid// }" ] && continue
			# Add to list with newline
			network_list="${network_list}${icon_wifi_1} ${ssid} (Signal: ${signal}%, Ch: ${chan})"$'\n'
		done <<< "$networks"
		
		# Remove trailing newlines - use sed to remove all trailing newlines
		network_list=$(echo "$network_list" | sed 's/\n*$//')
		
		echo "After trim, network_list: '${network_list:0:80}'" >> "$SDIR/wifi-connect.log"
		
		chosen=$(echo -e "${network_list}
${icon_close}  Back" | display_menu 1 "Network Information")
		
		echo "After display_menu, chosen='$chosen'" >> "$SDIR/wifi-connect.log"
		
		case "$chosen" in
			'') return ;;
			"$icon_close"*) return ;;
			*)
			# Extract SSID from the chosen line - remove icon at start and any trailing info
			ssid_info=$(echo "$chosen" | sed -E 's/^[^\ ]*//' | sed 's/ (Signal.*//' | xargs)
			# Show detailed info for this network
			show_network_details "$ssid_info"
			;;
		esac
	done
}

show_network_details() {
	local ssid="$1"
	# Debug
	echo "show_network_details called with SSID: '$ssid'" >> "$SDIR/wifi-connect.log"
	
	while true; do
		# Get all wifi info and search for our SSID using process substitution
		wifi_info=$(while IFS=: read -r s b c si se m; do
			[ "$s" = "$ssid" ] && echo "$s:$b:$c:$si:$se:$m"
		done < <(nmcli -t -f SSID,BSSID,CHAN,SIGNAL,SECURITY,MODE device wifi list))
		
		# Debug
		echo "wifi_info result: '$wifi_info'" >> "$SDIR/wifi-connect.log"
		
		if [ -z "$wifi_info" ]; then
			info_text="Network not found in scan results"
		else
			# Get the line for our SSID
			wifi_line=$(nmcli -t -f SSID dev wifi list | grep "^${ssid}$")
			
			if [ -z "$wifi_line" ]; then
				info_text="Network not found"
			else
				# Get full terse line and replace escaped colons with a marker
				# Format: SSID:BSSID:CHAN:SIGNAL:SECURITY:MODE
				full_line=$(nmcli -t -f SSID,BSSID,CHAN,SIGNAL,SECURITY,MODE dev wifi list | grep "^${ssid}:")
				
				# Replace escaped colons (\:) with a placeholder before splitting
				processed=$(echo "$full_line" | sed 's/\\:/@@/g')
				
				# Now extract fields
				ssid_extracted=$(echo "$processed" | cut -d: -f1)
				bssid_escaped=$(echo "$processed" | cut -d: -f2)
				chan=$(echo "$processed" | cut -d: -f3)
				signal=$(echo "$processed" | cut -d: -f4)
				security=$(echo "$processed" | cut -d: -f5)
				mode=$(echo "$processed" | cut -d: -f6)
				
				# Unescape BSSID - replace @@ with :
				bssid_unescaped="${bssid_escaped//@@/:}"
				
				# Get frequency from channel
				case "$chan" in
					[0-9]|[1][0-1]) freq="$((2400 + chan * 5)) MHz" ;;
					3[6-9]|4[0-8]) freq="5180 MHz" ;;
					5[0-4]|6[0-4]) freq="5260 MHz" ;;
					1[0-4][0-9]|1[0-4][0-4]) freq="5500 MHz" ;;
					14[9]|1[5-6][0-9]|16[0-5]) freq="5745 MHz" ;;
					*) freq="N/A" ;;
				esac
			fi
		fi
		
		# Check if saved
		saved="No"
		if nmcli -t -f NAME connection show 2>/dev/null | grep -qxF "$ssid"; then
			saved="Yes"
		fi
		
		# Check if connected
		connected="No"
		current_ssid=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
		[ "$current_ssid" = "$ssid" ] && connected="Yes"
		
		info_text="SSID: ${ssid}
BSSID: ${bssid_unescaped:-N/A}
Channel: ${chan:-N/A}
Frequency: ${freq:-N/A}
Signal: ${signal:-N/A}%
Security: ${security:-Open}
Mode: ${mode:-N/A}
Saved: ${saved}
Connected: ${connected}"
		
		# Format with close option - add newline before Back
		chosen=$(echo -e "${info_text}\n${icon_close}  Back" | display_menu 1 "Details: ${ssid}")
		
		case "$chosen" in
			'') return ;;
			"$icon_close"*) return ;;
		esac
	done
}

menu_main() {
	declare connection_state wifi_list options
	while true; do

		# Check for pending network from failed connection (Try Again)
		SDIR="$(dirname "$0")"
		try_again_network=$(cat "$SDIR/.pending_network" 2>/dev/null)
		
		# Check auto connection state
		if [ -f "$SDIR/.auto_connect" ]; then
			auto_connection_message="$icon_on  $tr_auto_connection_message"
		else
			auto_connection_message="$icon_off  $tr_auto_connection_message"
		fi
		
		# Small delay to let WiFi settle after failed connection
		[ -n "$try_again_network" ] && sleep 2
		
		connection_state=$(nmcli --colors no --get-values WIFI general)

		if [ "$connection_state" = "disabled" ]; then
			options="$enable_message\n$known_connections_message"
		elif [ "$connection_state" = "enabled" ]; then

			if [ -n "$submenu" ]; then
				options="$submenu_message"
			else
				# Check refresh cooldown (15 seconds)
				last_refresh=$(cat "$SDIR/.refresh_time" 2>/dev/null)
				current_time=$(date +%s)
				cooldown=15
				
				# Placeholder - will be updated after network count is known
				refresh_message="󰑙  Refresh Networks"
				
			# Add Try Again option if there's a pending network (for clickable option)
			if [ -n "$try_again_network" ]; then
				try_again_message="󰑙  𝙏𝙧𝙮 𝘼𝙜𝙖𝙞𝙣: $try_again_network"
				options="$disable_message\n${interfaces[1]:+$interface_message ${interface_to_use}\n}$known_connections_message\n${wireguard:+${wireguard_message}\n}$hidden_message\n$refresh_message\n$network_info_message\n$auto_connection_message\n$close_menu_message"
			else
				options="$disable_message\n${interfaces[1]:+$interface_message ${interface_to_use}\n}$known_connections_message\n${wireguard:+${wireguard_message}\n}$hidden_message\n$refresh_message\n$network_info_message\n$auto_connection_message\n$close_menu_message"
			fi
			fi

			echo "$tr_scanning_networks"
			wifi_list=$(nmcli --colors no --get-values SECURITY,SIGNAL,SSID,IN-USE device wifi list --rescan auto ifname $interface_to_use | awk -F ':' \
				-v wifi_1="$icon_wifi_1" \
				-v wifi_2="$icon_wifi_2" \
				-v wifi_3="$icon_wifi_3" \
				-v wifi_4="$icon_wifi_4" \
				-v wifi_5="$icon_wifi_5" \
				-v wifi_6="$icon_wifi_6" \
				-v check="$icon_check" \
				-v saved="$icon_saved_indicator" \
				-v tryagain="$try_again_network" \
			'
			BEGIN {
				# Get saved connections that have been connected at least once (timestamp > 0)
				while (("nmcli -t -f NAME,TIMESTAMP connection show 2>/dev/null" | getline line) > 0) {
					n = split(line, arr, ":")
					name = arr[1]
					ts = arr[2]
					# Exclude loopback, Wired, and connections never connected (timestamp = 0)
					if (name !~ /^lo$/ && name !~ /^Wired/ && ts > 0) {
						saved_arr[name] = 1
					}
				}
				close("nmcli -t -f NAME,TIMESTAMP connection show 2>/dev/null")
			}
			$3 {
				# Check if network is saved
				is_saved = ($3 in saved_arr) ? 1 : 0
					
				# Signal bars based on signal strength
				if ($2 >= 70)
					bars="󰢾"
				else if ($2 >= 50)
					bars="󰢽"
				else if ($2 >= 30)
					bars="󰢼"
				else
					bars="󰢿"
					
				if ($1 ~ /^WPA/)
					if ($2 > 80)
						sub($1, wifi_1)
					else if ($2 > 60)
						sub($1, wifi_2)
					else
						sub($1, wifi_3)
				else if ($1 == "")
					if ($2 > 80)
						sub($1, wifi_4)
					else if ($2 > 60)
						sub($1, wifi_5)
					else
						sub($1, wifi_6)
						
				# Truncate SSID if longer than 70 characters
				if (length($3) > 70)
					ssid = substr($3, 1, 67) "..."
				else
					ssid = $3
					
				# Use separate variable for connected network
				if ($4 == "*")
					connected = check "  " ssid " (connected) " bars (is_saved ? " 󱣪" : "")
				else if (tryagain != "" && $3 == tryagain)
					networks[y++] = wifi_1 "  " ssid " (𝙏𝙧𝙮 𝘼𝙜𝙖𝙞𝙣) " bars
				else if (is_saved)
					networks[y++] = $1 "  " ssid " " bars " 󱣪"
				else
					networks[y++] = $1 "  " ssid " " bars
			}
			END {
				# Print connected network first, then others
				if (connected) print connected
				for (i = 0; i < y; i++)
					print networks[i]
			}
			')
			echo "$tr_scanning_networks_complete"
			
			# Auto connection - connect to saved network if available and auto-connect is ON
			if [ -f "$SDIR/.auto_connect" ]; then
				# Get current connected network
				current_conn=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":wlan0" | cut -d: -f1)
				
				if [ -z "$current_conn" ]; then
					# Get list of saved connections with timestamps (connected before)
					while IFS=: read -r name ts; do
						[ -z "$name" ] && continue
						[ "$name" = "lo" ] && continue
						[[ "$name" =~ ^Wired ]] && continue
						[ "$ts" = "0" ] && continue
						
						# Check if this saved network is in the available wifi list
						if echo "$wifi_list" | grep -qF "$name"; then
							# Found a saved network that's available - connect to it
							echo "Auto-connecting to saved network: $name" >> "$SDIR/wifi-connect.log"
							
							# Try to connect - if saved connection exists and password unchanged, works without prompt
							nmcli_output=$(timeout 3 nmcli -a connection up id "$name" 2>&1)
							result=$?
							sleep 3
							
							# Check if connected
							if nmcli -t -f NAME,DEVICE connection show --active | grep -q ":wlan0"; then
								send_notification 1 1 "$tr_notice_connected_summary" "$tr_notice_connected_wifi_body"
								echo "Auto-connect success" >> "$SDIR/wifi-connect.log"
								exit 0
							else
								echo "Auto-connect failed for: $name, trying next..." >> "$SDIR/wifi-connect.log"
							fi
						fi
					done < <(nmcli -t -f NAME,TIMESTAMP connection show)
				fi
			fi
			
			# Count available networks (including connected)
			network_count=$(echo "$wifi_list" | wc -l | xargs)
			
			# Map number to bold font
			case "$network_count" in
				0) bold_num="𝟬" ;;
				1) bold_num="𝟭" ;;
				2) bold_num="𝟮" ;;
				3) bold_num="𝟯" ;;
				4) bold_num="𝟰" ;;
				5) bold_num="𝟱" ;;
				6) bold_num="𝟲" ;;
				7) bold_num="𝟳" ;;
				8) bold_num="𝟴" ;;
				9) bold_num="𝟵" ;;
				*) bold_num="$network_count" ;;
			esac
			
			# Update refresh_message with network count
			if [ -n "$last_refresh" ] && [ $((current_time - last_refresh)) -lt $cooldown ]; then
				refresh_message="󰑙  Refresh Networks [${bold_num}] (Recommended to Wait 15-20s before trying again)"
			else
				refresh_message="󰑙  Refresh Networks [${bold_num}]"
			fi
			
			# Update options with the new refresh_message
			if [ -n "$try_again_network" ]; then
				options="$disable_message\n${interfaces[1]:+$interface_message ${interface_to_use}\n}$known_connections_message\n${wireguard:+${wireguard_message}\n}$hidden_message\n$refresh_message\n$network_info_message\n$auto_connection_message\n$close_menu_message"
			else
				options="$disable_message\n${interfaces[1]:+$interface_message ${interface_to_use}\n}$known_connections_message\n${wireguard:+${wireguard_message}\n}$hidden_message\n$refresh_message\n$network_info_message\n$auto_connection_message\n$close_menu_message"
			fi

		fi

		chosen="$(echo -e "${options}${wifi_list:+\n}$wifi_list" | display_menu 1 "$tr_main_menu_prompt")"

		case "$chosen" in
			'') exit 0 ;;
			"$icon_config"*) menu_submenu ;;
			"$icon_wifi_enable"*) nmcli radio wifi on ; send_notification 1 1 "$tr_notice_enable_wifi_summary" "$tr_notice_enable_wifi_body" ; exit 0 ;;
			"$icon_wifi_disable"*) nmcli radio wifi off ; send_notification 1 1 "$tr_notice_disable_wifi_summary" "$tr_notice_disable_wifi_body" ; exit 0 ;;
			"$icon_interface"*) select_interface ;;
			"$icon_saved"*) menu_known_connections "wifi" ;;
			"$icon_dragon"*) menu_known_connections "wireguard" ;;
			"$icon_eye"*) connect_hidden ;;
			"$refresh_message")
				# Normal refresh - save time and restart
				SDIR="$(dirname "$0")"
				date +%s > "$SDIR/.refresh_time"
				exit 42
				;;
			"󰑙  Refresh Networks"*)
				# Normal refresh - save time and restart
				SDIR="$(dirname "$0")"
				date +%s > "$SDIR/.refresh_time"
				exit 42
				;;
			"󰑙  𝙏𝙧𝙮 𝘼𝙜𝙖𝙞𝙣:"*)
				# Try Again - clear pending and the network will appear in wifi list as unsaved
				# User can select it to be prompted for password
				rm -f "$SDIR/.pending_network"
				# Refresh the network list
				date +%s > "$SDIR/.refresh_time"
				exit 42
				;;
			"$icon_network_info"*)
				echo "Network Info clicked!" >> "$SDIR/wifi-connect.log"
				menu_network_info
				;;
			"$auto_connection_message")
				# Toggle auto connection
				if [ -f "$SDIR/.auto_connect" ]; then
					rm -f "$SDIR/.auto_connect"
				else
					touch "$SDIR/.auto_connect"
				fi
				exit 42
				;;
			"$icon_close_menu"*) exit 0 ;;
			*) connect_wifi "$chosen" ;;
		esac

	done
}

############################################################ MAIN ############################################################

# tr_* variables are for translation or customization (for editing in config file, not here!).
tr_scanning_networks='Scanning networks'
tr_scanning_networks_complete='Scanning completed'
tr_submenu_message='More options'
tr_disable_message='Disable Wi-Fi'
tr_enable_message='Enable Wi-Fi'
tr_interface_message='Interface:'
tr_known_connections_message='Known connections'
tr_remove_all_networks_message='Remove All Saved Networks'
tr_autoconnect_message='Autoconnect'
tr_ipv4_config_message='DHCP configuration'
tr_dns4_message='DNS IPv4'
tr_ipv6_config_message='IPv6 configuration'
tr_dns6_message='DNS IPv6'
tr_autoip_message='Automatic IP configuration'
tr_autodns_message='Automatic DNS'
tr_address_message='Addresses'
tr_gateway_message='Gateway:'
tr_forget_message='Forget connection'
tr_wireguard_message='Wireguard connections'
tr_wireguard_enable_message='Enable VPN'
tr_rename_connection_message='Rename connection'
tr_hidden_message='Connect to a hidden network'
tr_close_menu_message='Close the menu'
tr_network_info_message='Network Information'
tr_auto_connection_message='Auto Connection'
# refresh option removed - user can close menu and reopen for fresh scan
refresh_message="  Refresh Networks"

tr_main_menu_prompt='Wi-Fi SSID:'
tr_select_interface_prompt='Interface to use:'
tr_ask_password_prompt='Password:'
tr_menu_dns_prompt='New DNS:'
tr_menu_dns_sure_prompt_1='Remove DNS'
tr_menu_dns_sure_prompt_2='?'
tr_menu_ip_config_addresses_prompt='address1/CIDR_mask,address2/CIDR_mask,...'
tr_menu_ip_config_gateway_prompt='New gateway:'
tr_menu_addresses_prompt='New address:'
tr_menu_addresses_sure_prompt_1='Remove address'
tr_menu_addresses_sure_prompt_2='?'
tr_forget_connection_prompt='Connection to forget:'
tr_forget_connection_sure_prompt_1='Forget'
tr_forget_connection_sure_prompt_2='?'
tr_rename_connection_prompt='New name:'
tr_connect_hidden_prompt='Network name:'

tr_notice_connected_summary='Connected to network'
tr_notice_disconnected_summary='Disconnected from network'
tr_notice_error_summary='Connection error'
tr_notice_enable_wifi_summary='Wi-Fi enabled'
tr_notice_disable_wifi_summary='Wi-Fi disabled'
tr_notice_connected_wifi_body='Successful connection to Wi-Fi network'
tr_notice_disconnected_wifi_body='Successful disconnection from Wi-Fi network'
tr_notice_error_wifi_connection_body='An error occurred while trying to connect to the Wi-Fi network'
tr_notice_error_wifi_disconnection_body='An error occurred while trying to disconnect to the Wi-Fi network'
tr_notice_connected_vpn_body='Successful connection to VPN'
tr_notice_disconnected_vpn_body='Successful disconnection from VPN'
tr_notice_error_vpn_connection_body='An error occurred while trying to connect to the VPN'
tr_notice_error_vpn_disconnection_body='An error occurred while trying to disconnect to the VPN'
tr_notice_enable_wifi_body='Wi-Fi was successfully enabled'
tr_notice_disable_wifi_body='Wi-Fi was successfully disabled'

# Detecting Wi-Fi interfaces and add them to the array
mapfile -t interfaces < <(nmcli --colors no --get-values TYPE,DEVICE device status | awk -F ':' '$1 == "wifi" {print $2}')
if [ -z "${interfaces[0]}" ]; then
	echo "$program_name: No Wi-Fi interfaces detected." >&2
	exit 2
fi

# Default launcher (for editing in config file)
launcher='wofi'
# Custom launcher options
declare -A custom_opts
# Default icon display (for editing in config file)
emoji=
# Default menu display. Set variable to anything for submenu options (for editing in config file)
submenu=
# Default interface (edit in config file on your risk, if you know your hardware, or use --interface option instead)
interface_to_use="${interfaces[0]}"
# Default wireguard menus visibility. Set variable to anything for wireguard support (for editing in config file)
wireguard=
# Default is to check if notify-send is installed and, if it is, enable notifications
notifications=$(command -v notify-send &> /dev/null && echo 1)

program_name="$(basename $0)"

{ [ -n "$XDG_CONFIG_HOME" ] && [ -f "${XDG_CONFIG_HOME}/${program_name}/config" ] && . "${XDG_CONFIG_HOME}/${program_name}/config"; } ||
	{ [ -f "${HOME}/.config/${program_name}/config" ] && . "${HOME}/.config/${program_name}/config"; } ||
	{ [ -f "${HOME}/.${program_name}" ] && . "${HOME}/.${program_name}"; }

# Options
while [ -n "$1" ]; do
	case "$1" in
		'-h' | '--help') print_usage ;;
		'-v' | '--version') print_about ;;
		'-s' | '--submenu') submenu=1 ;;
		'-S' | '--no-submenu') submenu= ;;
		'-i' | '--interface')
			if [ ! $(nmcli --colors no --get-values TYPE,DEVICE device status | awk -F ':' '$1 == "wifi" {print $2}' | grep --word-regexp "$2") ]; then
				echo "$program_name: Unknown interface given: $2" >&2
				exit 2
			fi
			interface_to_use="$2"
			shift
			;;
		'-w' | '--wireguard') wireguard=1 ;;
		'-W' | '--no-wireguard') wireguard= ;;
		'-j' | '--emoji') emoji=1 ;;
		'-J' | '--no-emoji') emoji= ;;
		'--no-notify') notifications= ;;
		'--wofi') launcher='wofi' ;;
		'--rofi') launcher='rofi' ;;
		'--wmenu') launcher='wmenu' ;;
		'--dmenu') launcher='dmenu' ;;
		'--bemenu') launcher='bemenu' ;;
		'--custom')
			launcher='custom'
			custom_opts[launcher]="$2"
			custom_opts[insensitive]="$3"
			custom_opts[sensitive]="$4"
			custom_opts[password]="$5"
			shift 4
			;;
		*) echo "$program_name: Wrong option given. See usage with -h or --help." >&2 ; exit 1 ;;
	esac
	shift
done

if [ "$launcher" = 'custom' ]; then
	[ -n "${custom_opts[launcher]}" ] &&
	[ -n "${custom_opts[insensitive]}" ] &&
	[ -n "${custom_opts[sensitive]}" ] &&
	[ -n "${custom_opts[password]}" ] || {
	echo "$program_name: Custom launcher options not defined. See usage with -h or --help." >&2
	exit 4
}
fi

command -v ${custom_opts[launcher]:-$launcher} &> /dev/null || {
	echo "$program_name: The launcher selected is not installed: $launcher. See usage with -h or --help." >&2
	exit 3
}

# Icon variables
icon_dragon="${icon_dragon:-$([ -z "$emoji" ] && echo   || echo 🐉)}"
icon_config="${icon_config:-$([ -z "$emoji" ] && echo  || echo ⚙️)}"
icon_close="${icon_close:-$([ -z "$emoji" ] && echo  || echo ❌)}"
icon_disconnect="${icon_disconnect:-$([ -z "$emoji" ] && echo 󰤭 || echo 🔴)}"
icon_check="${icon_check:-$([ -z "$emoji" ] && echo  || echo ✅)}"
icon_saved_indicator="${icon_saved_indicator:-$([ -z "$emoji" ] && echo 󱣪 || echo 💾)}"
icon_eye="${icon_eye:-$([ -z "$emoji" ] && echo 󰛐 || echo 👁️)}"
icon_eye_closed="${icon_eye_closed:-$([ -z "$emoji" ] && echo 󰛑 || echo 🙈)}"
icon_saved="${icon_saved:-$([ -z "$emoji" ] && echo  || echo 💾)}"
icon_automatic="${icon_automatic:-$([ -z "$emoji" ] && echo 󱣲 || echo 🤖)}"
icon_wifi_enable="${icon_wifi_enable:-$([ -z "$emoji" ] && echo 󰖩 || echo 🌇)}"
icon_wifi_disable="${icon_wifi_disable:-$([ -z "$emoji" ] && echo 󰖪 || echo 🌃)}"
icon_wifi_1="${icon_wifi_1:-$([ -z "$emoji" ] && echo 󰤪 || echo 🚀🔒)}"
icon_wifi_2="${icon_wifi_2:-$([ -z "$emoji" ] && echo 󰤤 || echo 🚗🔒)}"
icon_wifi_3="${icon_wifi_3:-$([ -z "$emoji" ] && echo 󰤡 || echo 🦽🔒)}"
icon_wifi_4="${icon_wifi_4:-$([ -z "$emoji" ] && echo 󰤨 || echo 🚀)}"
icon_wifi_5="${icon_wifi_5:-$([ -z "$emoji" ] && echo 󰤢 || echo 🚗)}"
icon_wifi_6="${icon_wifi_6:-$([ -z "$emoji" ] && echo 󰤟 || echo 🦽)}"
icon_interface="${icon_interface:-$([ -z "$emoji" ] && echo 󰾲 || echo 🛰️)}"
icon_refresh="${icon_refresh:-$([ -z "$emoji" ] && echo 󰑙 || echo 🔄)}"
icon_refresh="${icon_refresh:-$([ -z "$emoji" ] && echo 󰑙 || echo 🔄)}"
icon_4_1="${icon_4_1:-$([ -z "$emoji" ] && echo 󰎭 || echo 🔧4️⃣)}"
icon_4_2="${icon_4_2:-$([ -z "$emoji" ] && echo 󰲦 || echo 🔍4️⃣)}"
icon_6_1="${icon_6_1:-$([ -z "$emoji" ] && echo 󰎳 || echo 🔧6️⃣)}"
icon_6_2="${icon_6_2:-$([ -z "$emoji" ] && echo 󰲪 || echo 🔍6️⃣)}"
icon_plug="${icon_plug:-$([ -z "$emoji" ] && echo 󱘖 || echo 🔌)}"
icon_trash="${icon_trash:-$([ -z "$emoji" ] && echo  || echo 🗑️)}"
icon_pen="${icon_pen:-$([ -z "$emoji" ] && echo 󰑕 || echo 📝)}"
icon_wireless="${icon_wireless:-$([ -z "$emoji" ] && echo 󰑩 || echo 🛜)}"
icon_net_1="${icon_net_1:-$([ -z "$emoji" ] && echo 󰩠 || echo 🤖)}"
icon_net_2="${icon_net_2:-$([ -z "$emoji" ] && echo 󰳘 || echo 🛣️)}"
icon_net_3="${icon_net_3:-$([ -z "$emoji" ] && echo 󰀑 || echo 🏠)}"
icon_net_4="${icon_net_4:-$([ -z "$emoji" ] && echo 󰖟 || echo 🌐)}"
icon_net_5="${icon_net_5:-$([ -z "$emoji" ] && echo 󰌘 || echo 💻)}"
icon_unlock="${icon_unlock:-$([ -z "$emoji" ] && echo  || echo 🔓)}"
icon_on="${icon_on:-$([ -z "$emoji" ] && echo  || echo 🟢)}"
icon_off="${icon_off:-$([ -z "$emoji" ] && echo  || echo 🔴)}"
icon_close_menu="${icon_close_menu:-$([ -z "$emoji" ] && echo  || echo ❎)}"
icon_network_info="${icon_network_info:-$([ -z "$emoji" ] && echo 󰈔 || echo ℹ)}"

# Messages with icons
submenu_message="$icon_config  $tr_submenu_message"
submenu_close_message="$icon_close  $tr_submenu_close_message"
disable_message="$icon_wifi_disable  $tr_disable_message"
enable_message="$icon_wifi_enable  $tr_enable_message"
interface_message="$icon_interface  $tr_interface_message"
known_connections_message="$icon_saved  $tr_known_connections_message"
remove_all_networks_message="$icon_trash  $tr_remove_all_networks_message"
autoconnect_message="$icon_automatic  $tr_autoconnect_message"
ipv4_config_message="$icon_4_1  $tr_ipv4_config_message"
dns4_message="$icon_4_2  $tr_dns4_message"
ipv6_config_message="$icon_6_1  $tr_ipv6_config_message"
dns6_message="$icon_6_2  $tr_dns6_message"
autoip_message="$icon_net_1  $tr_autoip_message"
autodns_message="$icon_net_4  $tr_autodns_message"
address_message="$icon_net_3  $tr_address_message"
gateway_message="$icon_net_2  $tr_gateway_message"
forget_message="$icon_trash  $tr_forget_message"
wireguard_message="$icon_dragon  $tr_wireguard_message"
wireguard_enable_message="$icon_plug  $tr_wireguard_enable_message"
rename_connection_message="$icon_pen  $tr_rename_connection_message"
hidden_message="$icon_eye  $tr_hidden_message"
close_menu_message="$icon_close_menu  $tr_close_menu_message"
network_info_message="$icon_network_info  $tr_network_info_message"

menu_main
